### ISSUE TITLE
FindBugs - StopWatch - Writing to static field (9 parts)

### ISSUE THREAD

**Issue by qnly1** [cst316/spring16project-Fortran#48]
1) Writing to static field StopWatch.hour from instance method: 
           - StopWatch$ResetEvent.actionPerformed(ActionEvent).
           - StopWatch$StartEvent.actionPerformed(ActionEvent). 
           - StopWatch$TimeClass.logic().

2) Writing to static field StopWatch.min from instance method:
           - StopWatch$ResetEvent.actionPerformed(ActionEvent).
           - StopWatch$StartEvent.actionPerformed(ActionEvent). 
           - StopWatch$TimeClass.logic().

3) Writing to static field StopWatch.sec from instance method:
           - StopWatch$ResetEvent.actionPerformed(ActionEvent).
           - StopWatch$StartEvent.actionPerformed(ActionEvent). 
           - StopWatch$TimeClass.logic().

**Comment by mazaval4** [comment]
Fixed the bugs. Commit number associated with the bug fixes is 5be788d51cbe25e893495accdc6ded07db6967a0
